### ISSUE TITLE
HW 5: q.beta converges to zero

### ISSUE THREAD

**Issue by davismj87** [eric-ward/safs-timeseries#11]
Hi all,

I'm having no trouble getting the simplified model in problem 1 to work, but when I try to add a covariate, my process error for the "slope" parameter converges to zero, so the parameter is not dynamic through time. Here's the code/output. I feel like I'm missing something obvious:

	Recruits = matrix(log(SRdata$Rec), nrow=1)
	Prop_Rec = matrix(log(SRdata$Rec/SRdata$Sp), nrow=1)
	Spawners = matrix(log(SRdata$Sp), nrow=1)
	TT = length(SRdata$brood.yr)
	m = dim(Spawners)[1] + 1

	#Process error#
	B = diag(m)
	U = matrix(0, nrow=m, ncol=1)		
	Q = matrix(list(0),m,m)			
	diag(Q) = c("q.alpha","q.beta")

	#Observation error#
	R = matrix("r")				
	Z = array(NA, c(1,m,TT)) 		
	Z[1,1,] = rep(1,TT) 
	Z[1,2,] = Spawners
	A = matrix(0)			
	inits.list = list(x0=matrix(c(0,0), nrow=m))
	mod.list = list(B=B, U=U, Q=Q, Z=Z, A=A, R=R)
	DLM.salmon3 = MARSS(Prop_Rec, inits=inits.list, model=mod.list, control=list(maxit=2000))

Log-likelihood: -48.51628 
AIC: 107.0326   AICc: 108.9076   
 
          Estimate
R.r          0.269
Q.q.alpha    0.316
Q.q.beta     0.000
x0.X1        1.344
x0.X2       -0.051

Standard errors have not been calculated. 
Use MARSSparamCIs to compute CIs and bias estimates.

The AICc value for this model is also greater than for the simplified model, so I get the feeling something's off. Same thing happens when I include PDO as a covariate. Am I setting up my matrices completely wrong?

**Comment by mdscheuerell** [comment]
Hi Melanie,

It's totally possible that there would be little/no data support for a model with a time-varying coefficient, in which case _q_ for beta could be zero.

Also, it is certainly possible that neither of the covariates offers a more parsimonious fit to the data. If that were the case, why do you think it might be? (_HINT_: Think about the specific time-varying parameters in each of the models, and what they represent.)
