### ISSUE TITLE
Hwk 4 Q2: Q not properly constrained

### ISSUE THREAD

**Issue by jessdiallo** [eric-ward/safs-timeseries#15]
For homework 4 on dynamic linear models, I'm getting stuck on question 2. I want the observation and process equations to be the following:

$$
log(R_t/S_t) = \alpha_t - bS_t + v_t \\
\alpha_t = \alpha_{t-1} + w_t
$$

My code is below. I'm getting an error that Q is not properly constrained, but I only want `alpha` to vary with time, not `b`. Please let me know if I set up the initial equations incorrectly or if there's a way to fix the MARSS error. Thanks!

## Code:

```
library(MARSS)
data(KvichakSockeye, package = "atsalibrary")
SR_data <- KvichakSockeye
# response variable
data <- ts(data = log(SR_data$Rec/SR_data$Sp), start = 1952, end = 1989, frequency = 1)
# z-score the predictor variable
Sp_z <- matrix((SR_data$Sp-mean(SR_data$Sp))/sqrt(var(SR_data$Sp)), nrow = 1)
m <- 2
TT <- length(data)

B <-  diag(m)
U <-  matrix(0, nrow = m, ncol = 1)
Q <- matrix(c("q.alpha", 0, 0, 0), nrow = 2)
Z <- array(NA, c(1, m, TT))  ## NxMxT; empty for now
Z[1,1,] <- rep(1, TT)        ## Nx1; 1's for intercept
Z[1,2,] <- Sp_z              ## Nx1; predictor variable 
A = matrix(0)
R <-  matrix("r")

inits_list <- list(x0 = matrix(c(0, 0), nrow = m))
mod_list <- list(B = B, U = U, Q = Q, Z = Z, A = A, R = R)

## fit the model with MARSS
dlm_fit <- MARSS(data, mod_list, inits = inits_list)
```
## Error message:
Errors were caught in is.marssMODEL()
Errors were caught in is.marssMODEL_marxss()
 The variance-covariance matrix Q is not properly constrained.
    Covariances and variances cannot be shared at t=1

**Comment by mdscheuerell** [comment]
Hi @jessdiallo. You have the right idea, but you can't mix both `numeric` and `character` data types in a matrix, **unless** you treat each element of the matrix as a list. Thus, you need something like

```
Q <- matrix(list("q.alpha", 0, 0, 0), nrow = 2)
```

**Comment by jessdiallo** [comment]
Thank you!
