### ISSUE TITLE
Q values estimated as zero in DLM

### ISSUE THREAD

**Issue by markusmin** [eric-ward/safs-timeseries#16]
When fitting a DLM, if our model output estimates the value of one value of the Q matrix as zero despite you allowing it to be non-zero, should this be interpreted as an issue with our model fitting or that our model is fitting correctly but determining that the best fit is without the time-varying effect of a covariate? I am happy to post a reprex if it's appropriate to do so for a homework assignment.

Here's what my Q matrix looks like and what the model output looks like - in this case it's the "Q.q.delta" value that's estimated as zero:
```
> Q
     [,1]      [,2]      [,3]
[1,] "q.alpha" 0         0   
[2,] 0         "q.delta" 0   
[3,] 0         0         0   
```

```
> fit_3

MARSS fit is
Estimation method: kem 
Convergence test: conv.test.slope.tol = 0.5, abstol = 0.001
Estimation converged in 679 iterations. 
Log-likelihood: -51.78324 
AIC: 115.5665   AICc: 117.8998  

Estimate
R.r       2.00e-01
Q.q.alpha 3.16e-01
Q.q.delta 0.00e+00
x0.X1     1.01e+00
x0.X2     2.85e-02
x0.X3     5.49e-06
Initial states (x0) defined at t=0

Standard errors have not been calculated. 
Use MARSSparamCIs to compute CIs and bias estimates.
```

Thanks!

**Comment by markusmin** [comment]
I just found that a similar question was asked three years ago in a [closed issue](https://github.com/nwfsc-timeseries/safs-timeseries/issues/11) which indicates that this result is plausible...

**Comment by mdscheuerell** [comment]
Hi @markusmin. Yes, you are correct. If there is no data support for an element of `Q` to be greater than 0, `MARSS()` may indeed set it to 0.
