### ISSUE TITLE
Problems installing atsar package

### ISSUE THREAD

**Issue by jessdiallo** [eric-ward/safs-timeseries#17]
I've tried various ways of installing the atsar package (restarting R studio, updating other packages first, updating R, selecting different options when prompted during the install), but I keep getting this error message:

devtools::install_github("nwfsc-timeseries/atsar")

`ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-atsar’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/0v/gmf2p3cj6jl70lg78pwyqhzc0000gn/T//RtmpNvBT1o/file1ae920c806f2/atsar_0.1.5.tar.gz’ had non-zero exit status`

Is there a simple way to remedy this?
Thank you!

--------------------
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16
other attached packages:
[1] rstantools_2.1.1     rstan_2.21.1

**Comment by eeholmes** [comment]
Did you remove that 00Lock file?

Eli

**Comment by jessdiallo** [comment]
Earlier today I tried that and couldn't find it in my folders, but by searching for it directly I was able to delete it and now the package is working! Thanks!
