### ISSUE TITLE
Confusion about lec_10_hmm slides

### ISSUE THREAD

**Issue by markusmin** [eric-ward/safs-timeseries#18]
I'm confused about the lecture slides for lecture 10 (Hidden Markov Models) - not sure if this is a typo or if I'm missing something.

On slide 19, it says this:

> There are two general flavours of transition matrices:
> 􏰀- Homogenous (or stationary), where transition probabilities don’t depend on t
> 􏰀- Non-homogeneous, where transition probabilities are time-varying
> 􏰀 In this class, we’ll only consider **homogeneous** cases

Then, on slide 21, there is an example where there is "a temporal trend in the transition probabilities" and there is a question in the homework that asks you to include "time varying parameters (e.g. year) in the means of each state, or state transition probabilities"

Is slide 19 a typo then, since the examples on slide 21 and in the homework are non-homogenous? Or am I misunderstanding the definition of homogenous vs. non-homogenous transition matrices.

**Comment by ericward-noaa** [comment]
Sorry Markus, and yes - that is confusing. I should edit those slides to clarify -- the case where time is included as a predictor in the transition probabilities -- does represent a non-homogenous example. So what I think we want you do do for the homework is model them as a function ~ time. Make sense?

**Comment by markusmin** [comment]
Thanks for the clarification Eric, that makes sense! I can close the issue now.
