### ISSUE TITLE
STATS package installation

### ISSUE THREAD

**Issue by davismj87** [eric-ward/safs-timeseries#6]
Hey Eric,

R is having issues installing the STATS package to my machine from github. It gives the following error message:

* installing *source* package 'STATS' ...
** R
** exec
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
During startup - Warning message:
package 'stats' in options("defaultPackages") was not found 
Error : package 'STATS' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/melaniedavis/Documents/R/R-3.3.0/library/STATS'
* restoring previous 'C:/Users/melaniedavis/Documents/R/R-3.3.0/library/STATS'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\melaniedavis\Documents\R\R-3.3.0\library\00LOCK-STATS\STATS\libs\x64\stats.dll to C:\Users\melaniedavis\Documents\R\R-3.3.0\library\STATS\libs\x64\stats.dll: Permission denied
Error: Command failed (1)

Any idea what's going on here?

Thanks,
Melanie

**Comment by vlahm** [comment]
Probably unrelated, but when I've had problems installing from GitHub in
the past, intalling/updating the "curl" package helped.

Mike

**Comment by davismj87** [comment]
Hmmmm still no dice.
