### ISSUE TITLE
HW3 problem 1.5c-e

### ISSUE THREAD

**Issue by bran1685** [eric-ward/safs-timeseries#7]
I am stuck on how to simulate the sample trajectories, not even sure where to start.  Please advise!

**Comment by eeholmes** [comment]
The question is asking for sample "trajectories".  It means population trajectories or your estimated whale population trajectories.  Not the *observed* but true.  So it is asking for simulated x's not simulated y's.

First you will need to get the estimated parameters from your fit.

coef(fit) #will do that

q = coef(fit)$Q
u = coef(fit)$U

#then you need to set x0 to the x estimate in 1997.  1997 is the last year in graywhales so you want the last state estimate

x0 = fit$states[1,39]  #take a look at fit$states

#now you are ready to write a for loop to create simulated data
#This is a really verbose way to do this, but easier to follow

#first set up a matrix to hold the simulated data
numyears = 10 #from part d we know we want to sim 10 years to 2007
simx = matrix(NA, 1000, numyears) #each row is going to be a simulated data set

#The you set up the outer for loop
for(nsim in 1:1000){
#now set up the x and y for this simulation
   x = rep(NA, numyears) #just a holder
   #now you have a for loop to walk through each year
   x[1] = you fill in this
   for(t in 2:numyears){
       x[t] = you fill in this
    }
    # now assign that x to simx
    simx[i,] = x
}  # next sim
