### ISSUE TITLE
HW4: looking for precisions

### ISSUE THREAD

**Issue by VincentOJ** [eric-ward/safs-timeseries#8]
Hi,

I was working on homework 4 and I stumbled upon some issues on the scope of some questions.

- When we are asked to plot the residuals and acf for each model, does it mean both state and model residuals? Should we show them for all the models (or only the best one for each question)? Should we comment what we see in the residuals and acfs? I am thinking yes to every question but I just wanted to check before I start coding and writing too much.
- I don't know how to tackle questions 0.5 and 0.6. How should we compare the results? Are we looking more at the coefficients? To what should we compare the lm and arima models? The best model out of questions 0.2 to 0.4? I am not sure how to be able to compare the lm models (or the arima ones) to anything I did in questions 0.3 and 0.4. 0.3 looked at the difference between observation and process when here we have either one or the other (lm or arima). 0.4 asked for different or the same coefficients for the functional groups. How can we achieve this in terms of regression or arima? Also, should we include a lagged variable in the regression? 

I am probably over thinking everything but a little guidance would be much appreciated.

Thanks!

**Comment by eeholmes** [comment]
Residuals: 
In general you should look at both the state and model residuals.
Just the best model is fine.
Yes, you should comment on whether the residual plots appear to show problems and what you think is going on if you do see problems.

**Comment by eeholmes** [comment]
For the homework you only need to do 5 not 6-7, unless you want to try those.

For #5.  For the lm versus MARSS comparison.  Using linear regression, or some variant of it, would be a typical approach to the sort of questions   in 1-4.  We want you to try that approach and see if you come up with different conclusions.  You would compare the estimated parameters and the conclusions that you make concerning the effects of temperature and TP.  Question 4 you simply cannot address by using a observation error only model.

Before you just do lm(dat ~ temperature + TP), step back and think about what that model is and whether it really addresses the questions---which relate to population growth.
